# Generated by Django 4.2.1 on 2023-06-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encryption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encryption',
            old_name='encryption_algorithm',
            new_name='algorithm',
        ),
    ]
